name: tubes_abp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2
  image: ^3.2.2
  http: ^1.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  universal_html: ^2.0.9
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  equatable: ^2.0.7
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/model/modelsampah.tflite
